[package]
name = "fastscraper-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
warp     = "0.3"
serde    = { version = "1.0", features = ["derive"] }
reqwest  = { version = "0.11", features = [
    "json",      # for serde JSON support
    "gzip",      # automatic gzip decompression
    "brotli",    # automatic Brotli decompression
    "deflate",   # automatic deflate decompression
    "stream",    # async streaming of bodies
    # "socks"    # uncomment if you need SOCKS5 proxy support
] }
tokio    = { version = "1.28", features = ["full"] }
